# Generated by Django 3.1.7 on 2021-03-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.URLField(),
        ),
    ]
