# Generated by Django 3.1.7 on 2021-03-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalog', '0002_auto_20210315_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'brand')},
        ),
    ]
